name: Build Sharingan Watchface

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Join SDK parts
      run: |
        cat .ciq/connectiq-sdk-win-8.2.2-2025-07-17-cf29b22d5.zip.0* > sdk.zip
        unzip -q sdk.zip -d sdk

    - name: Set execute permissions on SDK binaries
      run: |
        chmod +x sdk/*/bin/*

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build with monkeyc
      run: |
        sdk_dir=$(find $PWD/sdk -type d -name 'connectiq-sdk*' | head -n1)
        "$sdk_dir/bin/monkeyc" \
          -d fenix5 \
          -m manifest.xml \
          -z resources \
          -y mykey.der \
          -o Sharingan.PR3

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SharinganPR3
        path: Sharingan.PR3
